### PR TITLE
🔶 Add Sublime Text

### LINKED ISSUE #13: Sublime Text
I believe Sublime Text introduced/popularized the command palette as we know it (global, fuzzy, and stateful), I'm surprised it's not listed here!

### PR DESCRIPTION
**Pull request by Rnbsov**
Closes #13

### CODE REVIEW

**Comment by Rnbsov** [comment]
By the way, there is also [Vimium](https://github.com/philc/vimium) extension for browsers. It has vomnibar feature which is used to open URL, bookmark or history entry.  
  
I could make a PR if you consider it appropriate 😃

**Comment by stefanjudis** [comment]
Nice one! sublime was one of the first command bars I used. 🎉

**Comment by stefanjudis** [comment]
Re: vimium. Sure why not. :)

**Pull request merged**
